### ISSUE TITLE
journal_abbreviation()

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/bibfix#10]
Convert between abbreviated and long forms of journal names based on an updatable dataframe of abbreviations and full names. 

Support matching where journal cannot be found but there is an almost full match with abbreviated or unabbreviated journal name.

**Comment by nealhaddaway** [comment]
We could use this R package as a basis:
https://github.com/zoushucai/journalabbr

**Comment by DrMattG** [comment]
add journal_abbreviation function #15

**Comment by nealhaddaway** [comment]
Great start - thanks, @DrMattG! We just need to tidy the output so it's identical to the input bar the journal abbreviation, and add an optional parameter to set the output type (abbrev, abbrev with dots, full, CAPS, Title Case,...).

**Comment by ryan-carpenter** [comment]
Just an idea, @DrMattG , but somewhere I have link to a list of standard MEDLINE abbreviations. That is, the formula for abbreviating titles, not a list of the titles themselves. A possible shortcut might be to transform unmatched (unabbreviated) original names into an approximation of the target abbreviation. I don't really know R, so in pseudo code:
Regex_replace
- "((the journal)|joural) of" with "J"
- "[a-z]*ology" with "[a-z]*ol"
- "medicine" with "med",
- if no match, try making an acronym from the first letter of each word
- and so on.

While this might be a questionable approach, what I am certain of is that most people use only a small collection of titles, so a personalised list can take care of most of the title-changes at a much lower 'cost' than reading the full 87,000-title dataframe. Moreover, the variations of a particular title are always the same from a given database. One database might supply Journal of the American Medical Association (JAMA), or Journal of the American Medical Association, or JAMA, or something like Journal of the American Medical Association: the official journal for AMA members.
No problem. I don't even mind if I have to manually enter the abbreviation—once—if bibfix can apply my training to the next 57 articles from the same journal. It will not take long to build a custom list that bibfix can recognise and apply to all the journals important to me.
