### ISSUE TITLE
merge_bibliography()

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/bibfix#13]
Merge two bibliographic datasets, specifying which fields to keep from which input sources. 

Examples:
merge_bibliography(x = bib_data1, y = bib_data2, x_keep = title, abstract, y_keep = doi, url)

**Comment by ryan-carpenter** [comment]
The same field in two or more records may contain complementary information, so an option to combine the data from multiple records would be great. For example, I often want to keep all of the keywords from bib_data1 and bib_data2. A basic implementation would be to append the data from one record to the other. A more elegant approach would be to merge, sort, and remove duplicate keywords. This situation also occurs with URLs and note/comment fields.

**Comment by ryan-carpenter** [comment]
Jabref includes an option not to keep data from either record. Obviously, this is not the most critical use case, but it is helpful sometimes for clearing extraneous data, such as when the merged record contains the data in another field.
