### ISSUE TITLE
cr_works not working? 

### ISSUE THREAD

**Issue by befriendabacterium** [nealhaddaway/bibfix#19]
Hi folks, 

Tried to use the 'get_dois' function this morning and got a new rcrossref related error:

``` r

rcrossref::cr_works(query=missing_doi$title[a], sort = 'relevance')

## Error in cr_GET(endpoint = path, args, todf = FALSE, ...) : 
## res$response_headers$`content-type` == "application/json;charset=UTF-8" is not TRUE

```

This happens both on Neal's adapted/extended version of my original 'getDOIs' function (i.e. 'get_dois') and on the old 'getDOIs' function I wrote too, so I assume it goes deeper and is about something in rcrossref? Something to do with encoding, though the bibliographies I'm testing are supposed to be UTF-8. Not sure. Any ideas? Just raising it as a bug in case but feel free to close if i've gotten something wrong and it works fine for you.

**Comment by nealhaddaway** [comment]
Hmm - I’ll try to look into it. Might be worth moving over to the lens.org API, though…

Sent from my iPhone

On 29 Nov 2021, at 13:00, Matt Lloyd Jones ***@***.***> wrote:

﻿

Hi folks,

Tried to use the 'get_dois' function this morning and got a new rcrossref related error:

rcrossref::cr_works(query=missing_doi$title[a], sort = 'relevance')

## Error in cr_GET(endpoint = path, args, todf = FALSE, ...) :
## res$response_headers$`content-type` == "application/json;charset=UTF-8" is not TRUE


This happens both on Neal's adapted/extended version of my original 'getDOIs' function (i.e. 'get_dois') and on the old 'getDOIs' function I wrote too, so I assume it goes deeper and is about something in rcrossref? Something to do with encoding, though the bibliographies I'm testing are supposed to be UTF-8. Not sure. Any ideas? Just raising it as a bug in case but feel free to close if i've gotten something wrong and it works fine for you.

**Comment by nealhaddaway** [comment]
Yeah it's not working for me either - it's a fault with crossref. I'm getting an error for literally anything I enter into that call code.

**Comment by befriendabacterium** [comment]
There was actually some activity on this bug over on the rcrossref github repo this morning - might be a potential fix to do with having to specify the whole url, potentially? See here:

https://github.com/ropensci/rcrossref/issues/215#issuecomment-992442339

**Comment by nealhaddaway** [comment]
I was using the title, as in your example.. but maybe that's the wrong code for title searches?
