### ISSUE TITLE
Embase RIS missing "journal" - perhaps listed as "source" or something else? 

### ISSUE THREAD

**Issue by DrMattG** [nealhaddaway/bibfix#25]
From synthesisR issues - this is the file I used https://gitlab.com/extending-the-earcheck/living-review/-/blob/master/search/literature_search_02/Embase_290521_N974.RIS

**Comment by nealhaddaway** [comment]
Yeah - seems to be using ST (source title). If synthesisr doesn’t recognise this we could code for it to be used be journal is missing..? Would be good to work with Martin on this…

**Comment by DrMattG** [comment]
It should be an easy fix....(he says from the safety of a Norwegian Forest). Yeah let's try and see if we can propose a PR to synthesisr - I will have a look at it (probably next week now)

**Comment by nealhaddaway** [comment]
Haha Cool! Chris also did one for authors I think..

Sent from my iPhone

On 17 Mar 2022, at 19:24, Matthew Grainger ***@***.***> wrote:

﻿

It should be an easy fix....(he says from the safety of a Norwegian Forest). Yeah let's try and see if we can propose a PR to synthesisr - I will have a look at it (probably next week now)

**Comment by TNRiley** [comment]
Just jumped on to add this issue, but looks like you all are way ahead of the game :)

**Comment by nealhaddaway** [comment]
Thanks, Trevor! How is the error manifesting itself? Is journal missing on download?

Sent from my iPhone

On 6 Apr 2022, at 13:01, Trevor Riley ***@***.***> wrote:

﻿

Just jumped on to add this issue, but looks like you all are way ahead of the game :)

**Comment by DrMattG** [comment]
I have had a dig in to synthesisr and from the code there it should actual work - source is listed in the codedata file. I can not work out why it doesn't work.... so how about a fix in bibfix - like this: 

https://github.com/nealhaddaway/bibfix/blob/f0115c30dc5bdfa38016044f3fcf59eb34e49ea2/R/scan_file.R#L12

`#' Scan RIS file for damage
#' @examples
#' \dontrun{
#' library(openalex)
#' devtools::install_github("kth-library/openalex", dependencies = TRUE)
#' openalex_polite("neal_haddaway@hotmail.com")
#' library(openalexR)
#' file <- "Users/neal.haddaway/OneDrive - SEI/ESHackathon/4.Remote 2020/citationchaser private/archive/inst/shiny-examples/citationchaser/www/references.ris"
#' refs <- synthesisr::read_refs(file.choose())
#' report <- scan_file(refs)
#' }
scan_file <- function(refs){
  
  #convert all 'NA's to NAs
  refs[refs=="NA"]=NA

  # if source is used in the ris instead of journal (EMBASE .ris)
  if(!is.null(refs$source)==TRUE){refs$journal<-refs$source}
    
  #subset relevant columns, ignore the rest
  if(is.null(refs$source_type) == TRUE){refs$source_type <- NA}
  if(is.null(refs$author) == TRUE){refs$author <- NA}
  if(is.null(refs$year) == TRUE){refs$year <- NA}
  if(is.null(refs$title) == TRUE){refs$title <- NA}
  if(is.null(refs$journal) == TRUE){refs$journal <- NA}
  if(is.null(refs$volume) == TRUE){refs$volume <- NA}
  if(is.null(refs$issue) == TRUE){refs$issue <- NA}
  if(is.null(refs$start_page) == TRUE){refs$start_page <- NA}
  if(is.null(refs$end_page) == TRUE){refs$end_page <- NA}
  if(is.null(refs$abstract) == TRUE){refs$abstract <- NA}
  if(is.null(refs$doi) == TRUE){refs$doi <- NA}
  if(is.null(refs$publisher) == TRUE){refs$publisher <- NA}

  refs <- refs[c('source_type', "author", "year", "title", "journal", "volume", "issue", "start_page", "end_page", "abstract", "doi", "publisher")]
  
  #total records
  n_total <- nrow(refs)
  
  #number missing fields
  n_author <- sum(!is.na(refs$author))
  n_year <- sum(!is.na(refs$year))
  n_title <- sum(!is.na(refs$title))
  n_journal <- sum(!is.na(refs$journal))
  n_volume <- sum(!is.na(refs$volume))
  n_issue <- sum(!is.na(refs$issue))
  n_start_page <- sum(!is.na(refs$start_page))
  n_end_page <- sum(!is.na(refs$end_page))
  n_doi <- sum(!is.na(refs$doi))
  n_abstract <- sum(!is.na(refs$abstract))
  
  #number with DOIs
  with_doi <- n_doi
  
  #no doi but with title (findable)
  #create vectors of missing data for each row
  refs$missing_data <- ''
  for(i in 1:nrow(refs)){
    row <- refs[i,]
    missingCols <- paste0(names(refs)[which(is.na(row) == TRUE)], collapse = '; ')
    refs$missing_data[i] <- missingCols
  }
  
  #number complete
  n_complete <- nrow(subset(refs, missing_data ==''))

  #number findable (without DOI but with titles)
  n_findable_titles <- nrow(subset(subset(refs, missing_data != ''), (is.na(doi)==TRUE & is.na(title)==FALSE)))
  
  output <- list(n_complete = n_complete,
                 n_author = n_author,
                 n_year = n_year,
                 n_title = n_title,
                 n_journal = n_journal,
                 n_volume = n_volume,
                 n_issue = n_issue,
                 n_start_page = n_start_page,
                 n_end_page = n_end_page,
                 n_doi = n_doi,
                 n_abstract = n_abstract,
                 n_findable_titles = n_findable_titles,
                 n_total = n_total)
  
  return(output)
  
}
`
Then using this function with an EMBASE .ris 

`
refs <- synthesisr::read_refs(EMBASE.ris)
report <- scan_file(refs)
report
$n_complete
[1] 0

$n_author
[1] 965

$n_year
[1] 973

$n_title
[1] 974

$n_journal
[1] 974

$n_volume
[1] 956

$n_issue
[1] 922

$n_start_page
[1] 941

$n_end_page
[1] 0

$n_doi
[1] 649

$n_abstract
[1] 963

$n_findable_titles
[1] 326

$n_total
[1] 975

`

**Comment by DrMattG** [comment]
I added a pull request (https://github.com/nealhaddaway/bibfix/pull/27 ) but it might not be the best way to deal with this problem - so ignore or we can discuss further

**Comment by nealhaddaway** [comment]
Looks good to me - just wondering what would happen if a record lacked source but had journal - it would double it up, I guess? Does anyone have an EMBASE example file? Just trying to get up to speed...

**Comment by ryan-carpenter** [comment]
> Does anyone have an EMBASE example file?

A plain-text export of all fields from **Embase** shows the `SOURCE` and `SOURCE TITLE` fields in this format:
```
SOURCE
  Journal of Science (2022) 409 Article Number: 102938. Date of Publication: 15 Sep 2022
SOURCE TITLE
  Journal of Science
```

The same records when exported directly from Embase in **RIS** format show `SOURCE TITLE` as:
```
JF  - Journal of Science
JO  - J. Sci.
```

The abbreviated journal name can also have the form "J Sci". The Embase `SOURCE` field does not have a single equivalent in related RIS file.

* The journal title in `SOURCE` is really from `SOURCE TITLE`, which maps to `JF` and `JO` in RIS.
* The year (in parentheses, after the title) maps to `Y1`.
* In the example above, "409" comes from `VOLUME`, which of course, maps to `VL`.
* "Article number" is the tail end of the article's DOI, hence, part of the `DOI` and  `FULL TEXT LINK` fields, which map to `DO` and `L2`, respectively, in the RIS file.
* The Embase record does not have an "article number, but instead uses `PUI` for the Embase record ID and `MEDLINE PMID` for PubMed ID numbers. These map to `U2` and `C5`, respectively in the RIS file.
* `Date of Publication` comes from the Embase field `DATE OF PUBLICATION`, which has no match in the related the RIS file. The fields `AiP/IP ENTRY DATE` and `FULL RECORD ENTRY DATE` from Embase do appear in the RIS file, mapped to `U3` and `U4`, respectively.

**Comment by DrMattG** [comment]
[Link to an Embase RIS](https://gitlab.com/extending-the-earcheck/living-review/-/blob/master/search/literature_search_02/Embase_290521_N974.RIS)

**Comment by nealhaddaway** [comment]
Sorry for being dense - your suggested code is grand, @DrMattG - that will populate journal where it's missing but source is present. Love it! Will accept your PR now.

**Comment by nealhaddaway** [comment]
Fixed now :)

**Comment by TNRiley** [comment]
Saw this was resolved, but looks like I'm still running int othis issue.. My .ris definelty has journal titles, but when uploading the bar still shows 0% with journal titles. Assuming it's looking at the wrong metadata field..
![chrome-capture (4)](https://user-images.githubusercontent.com/89118428/163202533-7dec8c90-b509-494a-a3c5-ef8944ddcd1b.jpg)

**Comment by nealhaddaway** [comment]
Thanks, Trevor - I chose not to build any editing into the upload, so that's done during repair. But I guess I should add in an intermediate step prompting the user to select fields to use for those that seem missing. I'll have a think. The repair here is exactly Matt's suggestion tho - when journal is missing but source is present, it's ported over.
________________________________

**Comment by DrMattG** [comment]
Yeah- need to check that and put some defensive code in there - how about
this one:
https://gitlab.com/extending-the-earcheck/living-review/-/blob/master/search/literature_search_02/Embase_290521_N974.RIS
