### ISSUE TITLE
record_repair()

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/bibfix#3]
Use CrossRef (and Lens.org) API to fetch full bibliographic record (based on dois), fill in all missing fields and highlight any clashes

**Comment by nealhaddaway** [comment]
Possibly a wrapper for other get_() functions

**Comment by nealhaddaway** [comment]
Could specify in an optional setting that where a DOI exists the record is overwritten (except for the abstract, which is less commonly held on crossref).

**Comment by ryan-carpenter** [comment]
> … highlight any clashes

Preferably, with the ability to over-ride manual changes or protected words. The ideal would be 'non-destructive' editing, as in many photo-management applications. If bibfix 'remembered' the original state of a reference, then record_repair could highlight clashes with the original state only, and not with the current iteration. Among other things, I want my en-dashes, em-dashes and no-break spaces. 
Another example: maybe the original record came from CrossRef and had a typo in the title. I correct the title in my working copy, then later run record_repair() on my database. The CrossRef record still has a typo, so this record comes up as a conflict, which I review and dismiss, spending unecessary time on a record that has not changed. Maybe I should have excluded this record from the repair, but what if, for example, this was an e-print that I hope to update with the published volume and issue numbers, when available?
