### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/bibfix#5]
[Link to Google Doc for collectively identifying use cases](https://docs.google.com/document/d/1AnlM0VoRxDaePkeNyLVCa_XShkDgA45xoyxuTtp7cbM/edit?usp=sharing)

**Comment by ryan-carpenter** [comment]
@nealhaddaway, Great to see the appearance of the bibfix project. Repairing references is a constant challenge, and I have several uses cases to suggest. Would you like ideas added directly to the Google Doc?

**Comment by nealhaddaway** [comment]
Thanks, Ryan! The GDoc is mainly for the core team, but please do feel free to add them to this thread and we can curate the Doc accordingly! If you have ideas for functions you can also add them as separate issues. Thanks so much!

**Comment by ryan-carpenter** [comment]
Use case: correct data in the wrong field (including multiple data types appearing unparsed in a single field).
Records often come in slightly different formats from different databases, even when exported using the same nominal file type. Field mixups can also happen through conversion between file types (e.g., latex to biblatex). Applications that attempt to update records using a DOI or other identifier fail, because they look only in the expected field of the corrupt record and hence, cannot find the identifier to lookup.
Possible solution: search all fields for a regex match that looks like a doi or url.

**Comment by ryan-carpenter** [comment]
Use case: The input is two (or more) records representing the same article. The output is a *new* merged record, ideally with some indication of a relationship to the original records.
This comment stems from my experience with the de-duplication and automatic update functions of reference managers, which tend to have serious unwanted side effects. It is not always clear in advance what is going to happen to merged/de-duplicated/updated records, and the changes are usually not reversible, which can make a complete mess of a database in an instant. Some applications move duplicate records to the trash along with their unique data. Others merge the data into one record and delete the other, or merge the data into a new record and delete *both* of the source records.
I am not aware of any reference managers that merge or update records without altering or deleting the original copies. Of course, this thinking might just reflect the error of my ways. With a revtools-style approach, I could keep a version history in github. :-)

**Comment by nealhaddaway** [comment]
> Use case: correct data in the wrong field (including multiple data types appearing unparsed in a single field).
> Records often come in slightly different formats from different databases, even when exported using the same nominal file type. Field mixups can also happen through conversion between file types (e.g., latex to biblatex). Applications that attempt to update records using a DOI or other identifier fail, because they look only in the expected field of the corrupt record and hence, cannot find the identifier to lookup.
> Possible solution: search all fields for a regex match that looks like a doi or url.

I think one of the problems with this will be that where there is an incorrect read-in it usually cannot correctly recognise the entry start, so the number of records is not correct. Good idea to export all DOIs from a corrupted file, but I imagine that will correspond to so much data loss the user would want to try to correct the corruption further up the pipeline...

**Comment by nealhaddaway** [comment]
> Use case: The input is two (or more) records representing the same article. The output is a _new_ merged record, ideally with some indication of a relationship to the original records.
> This comment stems from my experience with the de-duplication and automatic update functions of reference managers, which tend to have serious unwanted side effects. It is not always clear in advance what is going to happen to merged/de-duplicated/updated records, and the changes are usually not reversible, which can make a complete mess of a database in an instant. Some applications move duplicate records to the trash along with their unique data. Others merge the data into one record and delete the other, or merge the data into a new record and delete _both_ of the source records.
> I am not aware of any reference managers that merge or update records without altering or deleting the original copies. Of course, this thinking might just reflect the error of my ways. With a revtools-style approach, I could keep a version history in github. :-)

Deduplication is definitely a sticky issue, thanks! Kaitlyn Hair has developed a great R package for deduplication (https://figshare.com/articles/conference_contribution/Identifying_duplicate_publications_with_the_ASySD_Automated_Systematic_Search_De-duplication_tool_Presentation_at_ESMARConf/13637753/1) - we can invite her to contribute to our usage of matching based on her package, though.

**Comment by ryan-carpenter** [comment]
> Deduplication is definitely a sticky issue, thanks! Kaitlyn Hair has developed a great R package for deduplication

Indeed. Kaitlyn has the right angle, which is to focus on the ultimate goal of avoiding duplicate _data sources_, as opposed to duplicate records or objects. From a practical perspective (to the literature reviewer), the conference abstract preceding an eventual publication is effectively a 'duplicate' (most of the time), even though the two records are obviously different. One situation where deduplication crosses over into record repair is when an early publication turns into a final version. If I have made corrections or added custom keywords to the early version, I want to transfer those edits to the final version. I don't care about keeping the DOI of the early publication as distinct from the final version. I only want to 'upgrade' the old record to incorporate the final bibliographic information.

**Comment by ryan-carpenter** [comment]
> I think one of the problems with this will be that where there is an incorrect read-in it usually cannot correctly recognise the entry start, so the number of records is not correct. Good idea to export all DOIs from a corrupted file, but I imagine that will correspond to so much data loss the user would want to try to correct the corruption further up the pipeline...

Fair enough. I am tossing some ideas into the bucket, knowing that there will be practicalities and priorities to consider. Keep in mind that correcting the problem further up the pipeline is often impossible or very burdensome. In my most recent experience with this issue, I would have gladly thrown away the entire record to replace it with crossref, medline, or any other complete record. The choices were (a) wrestle EndNote into a compatible output, (b) wrestle JabRef into successful import, (c) collect the references again, one by one, (d) move the project to Zotero, Citavi, back into EndNote, or some other platform that has its own, different set of complications, or (e) manually edit each reference until one or more identifiers became recognisable to JabRef. I chose (d) because JabRef stores the data in a single plain text file, which I can edit efficiently sans reference manager, with the help of my friend, Regex.

**Comment by nealhaddaway** [comment]
> > I think one of the problems with this will be that where there is an incorrect read-in it usually cannot correctly recognise the entry start, so the number of records is not correct. Good idea to export all DOIs from a corrupted file, but I imagine that will correspond to so much data loss the user would want to try to correct the corruption further up the pipeline...
> 
> Fair enough. I am tossing some ideas into the bucket, knowing that there will be practicalities and priorities to consider. Keep in mind that correcting the problem further up the pipeline is often impossible or very burdensome. In my most recent experience with this issue, I would have gladly thrown away the entire record to replace it with crossref, medline, or any other complete record. The choices were (a) wrestle EndNote into a compatible output, (b) wrestle JabRef into successful import, (c) collect the references again, one by one, (d) move the project to Zotero, Citavi, back into EndNote, or some other platform that has its own, different set of complications, or (e) manually edit each reference until one or more identifiers became recognisable to JabRef. I chose (d) because JabRef stores the data in a single plain text file, which I can edit efficiently sans reference manager, with the help of my friend, Regex.

Thanks, Ryan! I'm curious to know more about this use case - was the file corrupted on export? Or during management offline? Was the original file no longer available? Perhaps a solution here is to archive every version in a local file on the users harddrive so they can easily revert...?

**Comment by ryan-carpenter** [comment]
Use case: bibliographic data is perfectly intact, from any source other than PubMed. Desired output: the same record with the addition of a PubMed ID. Reason: several useful tools rely on PubMed IDs to access MEDLINE indexing. One simple example is the Yale MeSH analyzer.

**Comment by nealhaddaway** [comment]
> > Deduplication is definitely a sticky issue, thanks! Kaitlyn Hair has developed a great R package for deduplication
> 
> Indeed. Kaitlyn has the right angle, which is to focus on the ultimate goal of avoiding duplicate _data sources_, as opposed to duplicate records or objects. From a practical perspective (to the literature reviewer), the conference abstract preceding an eventual publication is effectively a 'duplicate' (most of the time), even though the two records are obviously different. One situation where deduplication crosses over into record repair is when an early publication turns into a final version. If I have made corrections or added custom keywords to the early version, I want to transfer those edits to the final version. I don't care about keeping the DOI of the early publication as distinct from the final version. I only want to 'upgrade' the old record to incorporate the final bibliographic information.

I think we would want to be really clear here that we're dealing with bibliographic data, so duplicates are just for records, not data, articles or studies. It's the index record that we're dealing with in this package: so articles referring to the same study (thesis chapter and published article) for example are not duplicate **records**.

**Comment by ryan-carpenter** [comment]
> … was the file corrupted on export? Or during management offline? Was the original file no longer available? Perhaps a solution here is to archive every version in a local file on the users harddrive so they can easily revert...?
It may have been something as simple as accidentally selecting the wrong output style in EndNote. More likely, it was because most of the references were AHRQ guidelines, rather than 'normal' journal articles. Choosing any reference type other than 'journal article' or 'generic' in EndNote is a recipe for trouble. By now, I have learned not to waste time attempting to make EndNote behave differently than it does, so I just rolled with it and fixed the references.

**Comment by nealhaddaway** [comment]
> Use case: bibliographic data is perfectly intact, from any source other than PubMed. Desired output: the same record with the addition of a PubMed ID. Reason: several useful tools rely on PubMed IDs to access MEDLINE indexing. One simple example is the Yale MeSH analyzer.

Cool - that's a useful additional function - get_IDs(). Lens.org has MAGID, PMID, PMCID, COREID, DOI and an internal lens_ID, but there are others as well (like WoS Accession Number...). I'll add that, thanks!

**Comment by ryan-carpenter** [comment]
> I think we would want to be really clear here that we're dealing with bibliographic data, so duplicates are just for records, not data, articles or studies. It's the index record that we're dealing with in this package: so articles referring to the same study (thesis chapter and published article) for example are not duplicate **records**.

Absolutely. Understood, though I may have gone slightly off-piste. The leap, I suppose, was in considering non-duplicate local records (different DOIs) as analagous to corresponding local and remote records (same DOIs)—because I sometimes use related local records to complete bibliographic fields (e.g., when I know the incomplete record has the same authors as it's companion paper). Abominable, I know, but I have not had consistent (automatic) success with CrossRef and ArXiv.
