### ISSUE TITLE
match_record()

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/bibfix#6]
Internal function to match records based on a hierarchy of information. Suggested order:

1. Identical DOI
2. Identical title AND journal AND year AND volume
3. Identical first 250 characters of the abstract
4. Partially matched title AND identical journal AND year AND volume

Partial matching could be done with stringdist or similar.

**Comment by nealhaddaway** [comment]
This package from Kailtyn Hair on deduplication might be a useful starting point for matching records:
https://figshare.com/articles/conference_contribution/Identifying_duplicate_publications_with_the_ASySD_Automated_Systematic_Search_De-duplication_tool_Presentation_at_ESMARConf/13637753/1

**Comment by ryan-carpenter** [comment]
I am not familiar with how stringdist works, but I know that white space and punctuation characters are enough to prevent most reference managers from finding matches. The licensed databases, such as Embase, tend to have more polished formatting, and often use en-dashes and em-dashes in the title. If stringdist or similar does not already handle these characters well, they might need some special attention.
